# SonarQube / SonarCloud – Frontend legacy (frontend/)
# Utilisé quand on scanne ce dossier séparément
sonar.projectKey=payment-platform-frontend-legacy
sonar.projectName=Payment Platform :: Frontend (legacy)
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**

sonar.javascript.lcov.reportPaths=coverage/payment-platform-ui/lcov.info,coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/payment-platform-ui/lcov.info,coverage/lcov.info

sonar.qualitygate.wait=true
sonar.scm.provider=git
