--liquibase formatted sql

--changeset platform:3 splitStatements:true

INSERT INTO permissions (code) VALUES
  ('ADMIN_MANAGE_ORGANIZATIONS'),
  ('ADMIN_MANAGE_USERS'),
  ('ADMIN_VIEW_AUDIT'),
  ('ADMIN_VIEW_STATS'),
  ('SUPPLIER_MANAGE_AGENTS'),
  ('SUPPLIER_MANAGE_PAYMENTS'),
  ('SUPPLIER_MANAGE_PRODUCTS'),
  ('SUPPLIER_MANAGE_STOCK'),
  ('SHOP_MANAGE_AGENTS'),
  ('SHOP_CREATE_PAYMENTS'),
  ('SHOP_CANCEL_PAYMENTS'),
  ('VIEW_PAYMENTS'),
  ('VIEW_NOTIFICATIONS');

INSERT INTO role_permissions (role_code, permission_code) VALUES
  ('SYSTEM_ADMIN', 'ADMIN_MANAGE_ORGANIZATIONS'),
  ('SYSTEM_ADMIN', 'ADMIN_MANAGE_USERS'),
  ('SYSTEM_ADMIN', 'ADMIN_VIEW_AUDIT'),
  ('SYSTEM_ADMIN', 'ADMIN_VIEW_STATS'),
  ('SYSTEM_ADMIN', 'VIEW_PAYMENTS'),
  ('SYSTEM_ADMIN', 'VIEW_NOTIFICATIONS'),
  ('SUPPLIER_ADMIN', 'SUPPLIER_MANAGE_AGENTS'),
  ('SUPPLIER_ADMIN', 'SUPPLIER_MANAGE_PAYMENTS'),
  ('SUPPLIER_ADMIN', 'SUPPLIER_MANAGE_PRODUCTS'),
  ('SUPPLIER_ADMIN', 'SUPPLIER_MANAGE_STOCK'),
  ('SUPPLIER_ADMIN', 'VIEW_PAYMENTS'),
  ('SUPPLIER_ADMIN', 'VIEW_NOTIFICATIONS'),
  ('SUPPLIER_AGENT', 'SUPPLIER_MANAGE_PAYMENTS'),
  ('SUPPLIER_AGENT', 'SUPPLIER_MANAGE_STOCK'),
  ('SUPPLIER_AGENT', 'VIEW_PAYMENTS'),
  ('SUPPLIER_AGENT', 'VIEW_NOTIFICATIONS'),
  ('SHOP_ADMIN', 'SHOP_MANAGE_AGENTS'),
  ('SHOP_ADMIN', 'SHOP_CREATE_PAYMENTS'),
  ('SHOP_ADMIN', 'SHOP_CANCEL_PAYMENTS'),
  ('SHOP_ADMIN', 'VIEW_PAYMENTS'),
  ('SHOP_ADMIN', 'VIEW_NOTIFICATIONS'),
  ('SHOP_AGENT', 'SHOP_CREATE_PAYMENTS'),
  ('SHOP_AGENT', 'SHOP_CANCEL_PAYMENTS'),
  ('SHOP_AGENT', 'VIEW_PAYMENTS'),
  ('SHOP_AGENT', 'VIEW_NOTIFICATIONS');
